basePath: /v1
definitions:
  entity.Note:
    properties:
      author:
        $ref: '#/definitions/entity.User'
      createdAt:
        type: string
      id:
        type: string
      message:
        type: string
      status:
        type: string
      updatedAt:
        type: string
    type: object
  entity.User:
    properties:
      createdAt:
        type: string
      email:
        type: string
      id:
        type: string
      updatedAt:
        type: string
      username:
        type: string
    type: object
  v1.ListResponse:
    properties:
      history:
        items:
          $ref: '#/definitions/entity.Note'
        type: array
    type: object
  v1.createNoteRequest:
    properties:
      message:
        example: example message
        type: string
    required:
    - message
    type: object
  v1.response:
    properties:
      error:
        example: message
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: A REST API backend application that can be used to manage personal
    notes.
  title: Go Notes API
  version: "1.0"
paths:
  /note:
    get:
      consumes:
      - application/json
      description: Show all notes
      operationId: notes
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.ListResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
      summary: Show notes
      tags:
      - note
    post:
      consumes:
      - application/json
      description: Create a new note
      operationId: notes
      parameters:
      - description: Set up translation
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1.createNoteRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Note'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
      summary: Create note
  /note/:id:
    put:
      consumes:
      - application/json
      description: update note by id
      operationId: update-note
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
      summary: Update note
      tags:
      - note
swagger: "2.0"
